.\" Manpage for desktop-arch-update-indicator.
.\" Contact pikatsuto@gmail.com to correct errors or typos.
.SH NAME
desktop-arch-update-indicator \- est la commande démarer par le service d'indication de mise a jours
.SH OPTIONS
desktop-arch-update-indicator --start \- est un équivalent de desktop-arch-update-indicator
desktop-arch-update-indicator --count_update \- mais a jours l'icone de desktop-arch-update-indicator avec le nombre de mise a jours en attente
desktop-arch-update-indicator --update \- lance les mise a jours (pacman, powerpill, yay) puis propose une réinstallation du karnel en qu'a de soucil
desktop-arch-update-indicator --conif \- lance la configuration du programe
.SH BUGS
No known bugs.
.SH AUTHOR
Pikatsuto (pikatsuto@gmail.com)